# -*- coding: utf-8 -*-
#
# Bases de données documentaires et distribuées documentation build configuration file, created by
# sphinx-quickstart on Fri Sep  5 15:57:35 2014.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# https://latte.ee.usyd.edu.au/Tools/authoring.html

import sys
import os

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath('.'))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# -- General configuration ------------------------------------------------

global_data_context = '' # @@NAME YOUR CONTEXT@@
global_data_entry_url = '' # @@URL TO COLLECT DATA@@
global_data_entry_method = 'POST'
global_data_subject_field_name = 'leco_subject_field'
global_data_verb_field_name =    'leco_verb_field'
global_data_object_field_name =  'leco_object_field'
global_data_context_field_name = 'leco_context_field'

# mathjax_path="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'Sphinx_ext.eqt',
    'Sphinx_ext.questions',
    'Sphinx_ext.iframe'
]

# E_QUESTION EXTENSION CONF
#
eqt_action = global_data_entry_url
eqt_id_field_name = global_data_verb_field_name
eqt_data_field_name = 'equestion_name'
numfig = True

# Passer la variable latex a private pour la compilation Latex

def setup(app):
    app.add_config_value('docstruct', '', True)
    app.add_config_value('cassandra', '', True)
    app.add_config_value('cassandratp', '', True)
    app.add_config_value('mongoquery', '', True)
    app.add_config_value('mrbasic', '', True)
    app.add_config_value('mongomapreduce', '', True)
    app.add_config_value('mongodbtp', '', True)
    app.add_config_value('mongodbtp2', '', True)
    app.add_config_value('introri', '', True)
    app.add_config_value('introrisolr', '', True)
    app.add_config_value('rankingS1', '', True)
    app.add_config_value('rankingS2', '', True)
    app.add_config_value('rankingS3', '', True)
    app.add_config_value('ritp', '', True)
    app.add_config_value('rielastic', '', True)
    app.add_config_value('cloud1', '', True)
    app.add_config_value('replication1', '', True)
    app.add_config_value('sharding', '', True)
    app.add_config_value('mapreduce', '', True)
    app.add_config_value('spark1', '', True)
    app.add_config_value('pigtp', '', True)
    app.add_config_value('pasfini', '', True)
    app.add_config_value('annales18', '', True)
    app.add_config_value('annales20', '', True)
    app.add_config_value('annales23', '', True)
    app.add_config_value('annales24', '', True)
	
docstruct = 'public'
cassandra = 'public'
cassandratp = 'private'
rielastic = 'private'
mongoquery = 'private'
mongomapreduce = 'private'
mrbasic = 'private'

mongodbtp = 'private'
mongodbtp2 = 'private'
introri = 'private'
rankingS1 = 'private'
rankingS2 = 'private'
rankingS3 = 'private'
ritp = 'private'
cloud1 = 'private'
replication1 = 'private'
sharding = 'private'
mapreduce = 'private'
spark1 = 'private'
pigtp = 'private'
annales18 = 'private'
annales20 = 'private'
annales23 = 'private'
annales24 = 'private'
pasfini = 'private'

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'Bases de données documentaires et distribuées'
copyright = u'2014-2025, Nicolas Travers, Raphaël Fournier S\'niehotta et Philippe Rigaux'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = 'Septembre 2024'
# The full version, including alpha/beta/rc tags.
release ='Septembre 2024'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'fr'

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build']

# The reST default role (used for this markup: `text`) to use for all
# documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
#keep_warnings = False


# -- Options for HTML output ----------------------------------------------
# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'agogo'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
    "headerbg": "#114723",
    "linkcolor": "#114723",
    "headercolor1": "#114723",
    "headercolor2": "#114723"
}

# Add any paths that contain custom themes here, relative to this directory.
#html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
html_title =  u'Bases de données documentaires et distribuées v<release> - Cours CNAM NFE204'

# A shorter title for the navigation bar.  Default is the same as html_title.
html_short_title = u'BD documentaires et distribuées, v<release>'

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#html_logo = None

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
#html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
#html_domain_indices = True

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = 'b3d'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
# The paper size ('letterpaper' or 'a4paper').
#'papersize': 'letterpaper',

# The font size ('10pt', '11pt' or '12pt').
'pointsize': '11pt',

# Additional stuff for the LaTeX preamble.
'preamble': u'\\usepackage{amsmath,amsthm,amssymb}',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
  ('index', 'b3d.tex', u'Bases de données documentaires et distribuées',
   u'Philippe Rigaux', 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False

# If true, show page references after internal links.
#latex_show_pagerefs = False

# If true, show URL addresses after external links.
#latex_show_urls = False

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
#latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'basesdedonnesdocumentairesetdistribues', u'Bases de données documentaires et distribuées Documentation',
     [u'Philippe Rigaux'], 1)
]

# If true, show URL addresses after external links.
#man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
  ('index', 'Basesdedonnesdocumentairesetdistribuees', u'Bases de données documentaires et distribuées Documentation',
   u'Philippe Rigaux', 'Basesdedonnesdocumentairesetdistribuees', 'One line description of project.',
   'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
#texinfo_appendices = []

# If false, no module index is generated.
#texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
#texinfo_no_detailmenu = False


# -- Options for Epub output ----------------------------------------------

# Bibliographic Dublin Core info.
epub_title = u'Bases de données documentaires et distribuées'
epub_author = u'Philippe Rigaux'
epub_publisher = u'Philippe Rigaux'
epub_copyright = u'2013-2020, Philippe Rigaux'

# The basename for the epub file. It defaults to the project name.
epub_basename = u'b3d'

# The HTML theme for the epub output. Since the default themes are not optimized
# for small screen space, using the same theme for HTML and epub output is
# usually not wise. This defaults to 'epub', a theme designed to save visual
# space.
#epub_theme = 'epub'

# The language of the text. It defaults to the language option
# or en if the language is not set.
#epub_language = ''

# The scheme of the identifier. Typical schemes are ISBN or URL.
#epub_scheme = ''

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#epub_identifier = ''

# A unique identification for the text.
#epub_uid = ''

# A tuple containing the cover image and cover page html template filenames.
#epub_cover = ()

# A sequence of (type, uri, title) tuples for the guide element of content.opf.
#epub_guide = ()

# HTML files that should be inserted before the pages created by sphinx.
# The format is a list of tuples containing the path and title.
#epub_pre_files = []

# HTML files shat should be inserted after the pages created by sphinx.
# The format is a list of tuples containing the path and title.
#epub_post_files = []

# A list of files that should not be packed into the epub file.
#epub_exclude_files = []

# The depth of the table of contents in toc.ncx.
#epub_tocdepth = 3

# Allow duplicate toc entries.
#epub_tocdup = True

# Choose between 'default' and 'includehidden'.
#epub_tocscope = 'default'

# Fix unsupported image types using the PIL.
#epub_fix_images = False

# Scale large images.
#epub_max_image_width = 0

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#epub_show_urls = 'inline'

# If false, no index is generated.
#epub_use_index = True


# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'http://docs.python.org/': None}
